var imgdata = [
  {
    filename: "Shiny_Rat_Race.png",
    authors: ["ciran", "dawolfkid"],
    oga_theme: "Rat Race",
    month_numerical: 8,
    year: 2025,
  },
  {
    filename: "PYzvngL.png",
    authors: ["ciran"],
    oga_theme: "Summer of Labubu",
    month_numerical: 7,
    year: 2025,
  },
  {
    filename: "June2025_WrongPride-flat.png",
    authors: ["ciran"],
    oga_theme: "The Wrong Pride",
    month_numerical: 6,
    year: 2025,
  },
  {
    filename: "Mj2JMex.png",
    authors: ["ciran"],
    oga_theme: "Weather Warriors",
    month_numerical: 5,
    year: 2025,
  },
  {
    filename: "IMG_1352.png",
    authors: ["chimera", "dawolfkid"],
    oga_theme: "PokéPranks",
    month_numerical: 4,
    year: 2025,
  },
  {
    filename: "29Mar2025_AtlA2.png",
    authors: ["ciran"],
    oga_theme: "The Last Airbender",
    month_numerical: 3,
    year: 2025,
  },
  {
    filename: "hxEAbvb.png",
    authors: ["ciran"],
    oga_theme: "Animation Attack",
    month_numerical: 2,
    year: 2025,
  },
  {
    filename: "25Jan2025_LunarNewYear2.png",
    authors: ["ciran"],
    oga_theme: "Year of the Wood Dragon",
    month_numerical: 1,
    year: 2025,
  },
  {
    filename: "12282024_Holiday-animated.gif",
    authors: ["ciran"],
    oga_theme: "Beach Vacation in December",
    month_numerical: 12,
    year: 2024,
  },
  {
    filename: "11302024_FFiasco.png",
    authors: ["ciran"],
    oga_theme: "Festive Fiasco",
    month_numerical: 11,
    year: 2024,
  },
  {
    filename: "zw6Jcs8.png",
    authors: ["ciran"],
    oga_theme: "Creepy Cryptids",
    month_numerical: 10,
    year: 2024,
  },
  {
    filename: "PMEXOGA.png",
    authors: ["chimera"],
    oga_theme: "Pokémon Masters EX",
    month_numerical: 9,
    year: 2024,
  },
  ,
  {
    filename: "03312024_Pokeathlon.png",
    authors: ["ciran"],
    oga_theme: "Pokéathlon",
    month_numerical: 8,
    year: 2024,
  },
  {
    filename: "07272024_DoodleDread.png",
    authors: ["ciran"],
    oga_theme: "Ciran's Doodle Dread",
    month_numerical: 7,
    year: 2024,
  },
  {
    filename: "06292024_Rainbow.png",
    authors: ["ciran"],
    oga_theme: "Rainbow",
    month_numerical: 6,
    year: 2024,
  },
  {
    filename: "05252024_Circus.png",
    authors: ["ciran"],
    oga_theme: "Circus",
    month_numerical: 5,
    year: 2024,
  },
  {
    filename: "042024_esclipse.png",
    authors: ["ciran"],
    oga_theme: "Solar Eclipse",
    month_numerical: 4,
    year: 2024,
  },
  {
    filename: "03302024_Pasta.png",
    authors: ["ciran"],
    oga_theme: "Pokémon Pasta ",
    month_numerical: 3,
    year: 2024,
  },
  {
    filename: "7axg66W.png",
    authors: ["ciran"],
    oga_theme: "Year of the Wood Dragon",
    month_numerical: 2,
    year: 2024,
  },
  {
    filename: "WiFjtxg.png",
    authors: ["ciran"],
    oga_theme: "Pokémon Mystery Dungeon",
    month_numerical: 1,
    year: 2024,
  },
  {
    filename: "DTfu7QJ.gif",
    authors: ["ciran"],
    oga_theme: "The Indigo Disk",
    month_numerical: 12,
    year: 2023,
  },
];
