var imgdata = [
  {
    filename: "Shiny_Rat_Race.png",
    authors: ["ciran", "dawolfkid"],
    oga_theme: "Rat Race",
    month_numerical: 8,
    year: 2025,
  },
  {
    filename: "PYzvngL.png",
    authors: ["ciran"],
    oga_theme: "Summer of Labubu",
    month_numerical: 7,
    year: 2025,
  },
  {
    filename: "June2025_WrongPride-flat.png",
    authors: ["ciran"],
    oga_theme: "The Wrong Pride",
    month_numerical: 6,
    year: 2025,
  },
  {
    filename: "Mj2JMex.png",
    authors: ["ciran"],
    oga_theme: "Weather Warriors",
    month_numerical: 5,
    year: 2025,
  },
  {
    filename: "IMG_1352.png",
    authors: ["chimera", "dawolfkid"],
    oga_theme: "Pok\u00E9Pranks",
    month_numerical: 4,
    year: 2025,
  },
  {
    filename: "29Mar2025_AtlA2.png",
    authors: ["ciran"],
    oga_theme: "The Last Airbender",
    month_numerical: 3,
    year: 2025,
  },
  {
    filename: "hxEAbvb.png",
    authors: ["ciran"],
    oga_theme: "Animation Attack",
    month_numerical: 2,
    year: 2025,
  },
  {
    filename: "25Jan2025_LunarNewYear2.png",
    authors: ["ciran"],
    oga_theme: "Year of the Wood Dragon",
    month_numerical: 1,
    year: 2025,
  },
  {
    filename: "12282024_Holiday-animated.gif",
    authors: ["ciran"],
    oga_theme: "Beach Vacation in December",
    month_numerical: 12,
    year: 2024,
  },
];
