var imgdata = [
  {
    filename: "Shiny_Rat_Race.png",
    authors: ["ciran", "dawolfkid"],
    oga_theme: "Rat Race",
    month_numerical: 8,
    year: 2025,
  },
  {
    filename: "PYzvngL.png",
    authors: ["ciran"],
    oga_theme: "Summer of Labubu",
    month_numerical: 7,
    year: 2025,
  },
  {
    filename: "June2025_WrongPride-flat.png",
    authors: ["ciran"],
    oga_theme: "The Wrong Pride",
    month_numerical: 6,
    year: 2025,
  },
  {
    filename: "Mj2JMex.png",
    authors: ["ciran"],
    oga_theme: "Weather Warriors",
    month_numerical: 5,
    year: 2025,
  },
  {
    filename: "IMG_1352.png",
    authors: ["chimera", "dawolfkid"],
    oga_theme: "PokéPranks",
    month_numerical: 4,
    year: 2025,
  },
  {
    filename: "29Mar2025_AtlA2.png",
    authors: ["ciran"],
    oga_theme: "The Last Airbender",
    month_numerical: 3,
    year: 2025,
  },
  {
    filename: "hxEAbvb.png",
    authors: ["ciran"],
    oga_theme: "Animation Attack",
    month_numerical: 2,
    year: 2025,
  },
  {
    filename: "25Jan2025_LunarNewYear2.png",
    authors: ["ciran"],
    oga_theme: "Year of the Wood Dragon",
    month_numerical: 1,
    year: 2025,
  },
  {
    filename: "12282024_Holiday-animated.gif",
    authors: ["ciran"],
    oga_theme: "Beach Vacation in December",
    month_numerical: 12,
    year: 2024,
  },
  {
    filename: "11302024_FFiasco.png",
    authors: ["ciran"],
    oga_theme: "Festive Fiasco",
    month_numerical: 11,
    year: 2024,
  },
  {
    filename: "zw6Jcs8.png",
    authors: ["ciran"],
    oga_theme: "Creepy Cryptids",
    month_numerical: 10,
    year: 2024,
  },
  {
    filename: "PMEXOGA.png",
    authors: ["chimera"],
    oga_theme: "Pokémon Masters EX",
    month_numerical: 9,
    year: 2024,
  },
  {
    filename: "03312024_Pokeathlon.png",
    authors: ["ciran"],
    oga_theme: "Pokéathlon",
    month_numerical: 8,
    year: 2024,
  },
  {
    filename: "07272024_DoodleDread.png",
    authors: ["ciran"],
    oga_theme: "Ciran's Doodle Dread",
    month_numerical: 7,
    year: 2024,
  },
  {
    filename: "06292024_Rainbow.png",
    authors: ["ciran"],
    oga_theme: "Rainbow",
    month_numerical: 6,
    year: 2024,
  },
  {
    filename: "05252024_Circus.png",
    authors: ["ciran"],
    oga_theme: "Circus",
    month_numerical: 5,
    year: 2024,
  },
  {
    filename: "042024_esclipse.png",
    authors: ["ciran"],
    oga_theme: "Solar Eclipse",
    month_numerical: 4,
    year: 2024,
  },
  {
    filename: "03302024_Pasta.png",
    authors: ["ciran"],
    oga_theme: "Pokémon Pasta ",
    month_numerical: 3,
    year: 2024,
  },
  {
    filename: "7axg66W.png",
    authors: ["ciran"],
    oga_theme: "Year of the Wood Dragon",
    month_numerical: 2,
    year: 2024,
  },
  {
    filename: "WiFjtxg.png",
    authors: ["ciran"],
    oga_theme: "Pokémon Mystery Dungeon",
    month_numerical: 1,
    year: 2024,
  },
  {
    filename: "DTfu7QJ.gif",
    authors: ["ciran"],
    oga_theme: "The Indigo Disk",
    month_numerical: 12,
    year: 2023,
  },
  {
    filename: "L8ydUyz.png",
    authors: ["chimera", "ciran", "swiffix"],
    oga_theme: "Tarot Time",
    month_numerical: 11,
    year: 2023,
  },
  {
    filename: "cQF4MHH.png",
    authors: ["chimera"],
    oga_theme: "Aloha VGC",
    month_numerical: 10,
    year: 2023,
  },
  {
    filename: "F2boDWt.png",
    authors: ["chimera"],
    oga_theme: "The Teal Mask",
    month_numerical: 9,
    year: 2023,
  },
  {
    filename: "v6jFVTO.png",
    authors: ["ciran"],
    oga_theme: "A Swashbuckling Giveaway",
    month_numerical: 8,
    year: 2023,
  },
  {
    filename: "NYUJEAG.png",
    authors: ["ciran"],
    oga_theme: "Christmas in July",
    month_numerical: 7,
    year: 2023,
  },
  {
    filename: "MVIg3nQ_d.webp",
    authors: ["ciran"],
    oga_theme: "Dragon Ball Z",
    month_numerical: 6,
    year: 2023,
  },
  {
    filename: "1MCpq18.png",
    authors: ["ciran"],
    oga_theme: "Rivals",
    month_numerical: 4,
    year: 2023,
  },
  {
    filename: "x7A8uWK.png",
    authors: ["ciran"],
    oga_theme: "Gotta Ketchem All",
    month_numerical: 3,
    year: 2023,
  },
  {
    filename: "8Wqafxg.png",
    authors: ["ciran", "chimera"],
    oga_theme: "Valentine's Day",
    month_numerical: 2,
    year: 2023,
  },
  {
    filename: "7fkGD9S.png",
    authors: ["ciran"],
    oga_theme: "Year of the Rabbit",
    month_numerical: 1,
    year: 2023,
  },
  {
    filename: "w3ERKVL.png",
    authors: ["ciran", "swiffix", "chimera"],
    oga_theme: "Super Smash Bros.",
    month_numerical: 5,
    year: 2023,
  },
  {
    filename: "FuZ90To.png",
    authors: ["ciran"],
    oga_theme: "EVERY WICH GiveaWAY",
    month_numerical: 12,
    year: 2022,
  },
  {
    filename: "FhiiUFH.png",
    authors: ["ciran"],
    oga_theme: "Goodbye Galar Gala",
    month_numerical: 10,
    year: 2022,
  },
  {
    filename: "GOmNV6C.png",
    authors: ["ciran"],
    oga_theme: "Sheathing the Sword & Stowing the Shield",
    month_numerical: 9,
    year: 2022,
  },
  {
    filename: "HPf4Kgs.png",
    authors: ["ciran"],
    oga_theme: "Arm-ored Pokémon",
    month_numerical: 8,
    year: 2022,
  },
  {
    filename: "Unicorns_OGA.png",
    authors: ["ciran", "swiffix"],
    oga_theme: "Beautiful Unicorns",
    month_numerical: 7,
    year: 2022,
  },
  {
    filename: "H1hY27v.png",
    authors: ["ciran"],
    oga_theme: "Ancient Egypt",
    month_numerical: 6,
    year: 2022,
  },
  {
    filename: "KAjsazN.jpeg",
    authors: ["ciran", "swiffix"],
    oga_theme: "Checkmate!",
    month_numerical: 5,
    year: 2022,
  },
  {
    filename: "B3fzBT5.png",
    authors: ["ciran"],
    oga_theme: "Dungeons and Pokémon",
    month_numerical: 4,
    year: 2022,
  },
  {
    filename: "ZTAGa59.png",
    authors: ["ciran"],
    oga_theme: "Aquamarine",
    month_numerical: 3,
    year: 2022,
  },
  {
    filename: "eVXwOpM.png",
    authors: ["ciran"],
    oga_theme: "Year of the Water Tiger",
    month_numerical: 2,
    year: 2022,
  },
  {
    filename: "JxyNUAk.png",
    authors: ["ciran"],
    oga_theme: "Creation of Hisui & Sinnoh of Old!",
    month_numerical: 1,
    year: 2022,
  },
];
